const quotes = [
  "Believe in yourself!",
  "Stay positive, work hard, make it happen.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "You define your own life. Don’t let other people write your script.",
  "You are enough just as you are.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Don’t let yesterday take up too much of today.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "The way to get started is to quit talking and begin doing.",
  "The only impossible journey is the one you never begin.",
  "Act as if what you do makes a difference. It does.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "To be the best, you must be able to handle the worst.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Believe you can and you’re halfway there.",
  "Your passion is waiting for your courage to catch up.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "We generate fears while we sit. We overcome them by action.",
  "The only place where success comes before work is in the dictionary.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "If you want to achieve greatness stop asking for permission.",
  "The best revenge is massive success.",
  "Do not be embarrassed by your failures, learn from them and start again.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "If you are not willing to risk the usual you will have to settle for the ordinary.",
  "If you genuinely want something, don’t wait for it – teach yourself to be impatient.",
  "Do one thing every day that scares you.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "Life is not about finding yourself. Life is about creating yourself.",
  "The successful warrior is the average man, with laser-like focus.",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan.",
  "A goal is a dream with a deadline.",
  "If you want to lift yourself up, lift up someone else.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Don’t be afraid to give up the good to go for the great.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "Failure is the condiment that gives success its flavor.",
  "Success is the sum of small efforts, repeated day-in and day-out.",
  "You must expect great things of yourself before you can do them.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is not in what you have, but who you are.",
  "With self-discipline most anything is possible.",
  "The way to get started is to quit talking and begin doing.",
  "Don’t let what you cannot do interfere with what you can do.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "The only place where success comes before work is in the dictionary.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The ones who are crazy enough to think they can change the world, are the ones that do.",
  "Stop chasing the money and start chasing the passion.",
  "Don’t be afraid to give up the good to go for the great.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Opportunities don't happen. You create them.",
  "Try not to become a man of success. Rather become a man of value.",
  "Never give in except to convictions of honor and good sense.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."
];
